agents:
  - id: "glm-4.5"
    backend:
      type: "zai"
      model: "glm-4.5"
      base_url: "https://api.z.ai/api/paas/v4/"

  - id: "gemini-2.5-flash"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      enable_web_search: true

  - id: "claude-haiku-4-5-20251001"
    backend:
      type: "claude"
      model: "claude-haiku-4-5-20251001"
      enable_web_search: true
      enable_code_execution: true


ui:
  display_type: "textual_terminal"
  logging_enabled: true

